### ISSUE TITLE
Multi-line?

### ISSUE THREAD

**Issue by wrabit** [Diegovsky/htmeta#1]
I’m wondering if there a way to deal with an element that may have many attributes to try and keep definitions compact? i.e is there a way to achieve some formatted, multi line statement?

```
!DOCTYPE html
html {
    body {
        a text="Welcome!"
             onclick=“dosomething()”
             class=“primary”
             id=“1”    
    }
}
```

**Comment by Diegovsky** [comment]
ah yes, you can do that using \ to escape newlines, like so:
```
!DOCTYPE html
html {
    body {
        a text="Welcome!" \
             onclick=“dosomething()” \
             class=“primary” \
             id=“1”    
    }
}
```

**Comment by Diegovsky** [comment]
You can check out other special rules for stuff like multi-line strings here: https://kdl.dev/
